# Generated by Django 5.0 on 2024-01-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('core.basemodel',),
        ),
    ]
