# Generated by Django 5.0 on 2024-01-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='developers_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
