# Generated by Django 5.0 on 2024-01-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='youtube.com', max_length=1000),
        ),
    ]
