# Generated by Django 5.0 on 2024-01-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(default='https://youtube.com/', max_length=1000),
        ),
    ]
